<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='/style.css' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <h1>Product page</h1>
        <div class="product">
            <a href="/product/<?=$product['id']?>">
            <p class="name"><?=$product['name']?></p>
            <p class="img"><img src="<?=$product['image_url']?>"/></p>
            </a>
        </div>
    </body>
</html>
